An upcoming change to the Dart SDK will change the signature
dart-lang/http_server pull request #57
Opened 2019-06-22 19:33 UTC by tvolkert

of `File.openRead()` from returning `Stream<List<int>>` to
returning `Stream<Uint8List>`.

This forwards-compatible change prepares for that SDK breaking
change by casting the Stream to `List<int>` before transforming
it.

dart-lang/sdk#36900

2019-06-22 19:36 UTC, tvolkert commented
@kevmoo PTAL

2019-06-24 16:26 UTC, kevmoo requested changes

2019-06-24 16:26 UTC, kevmoo commented on pubspec.yaml
> +version: 0.9.8+2
Please add a note to the changelog!

2019-06-25 00:45 UTC, tvolkert commented on pubspec.yaml
> +version: 0.9.8+2
Done

2019-06-25 00:46 UTC, tvolkert commented
PTAL

2019-06-25 02:19 UTC, kevmoo approved these changes

2019-06-25 02:19 UTC, kevmoo commented
@tvolkert – did we give you commit rights yet?

2019-06-25 02:21 UTC, tvolkert commented
Nope

2019-06-25 02:26 UTC, kevmoo commented
Want me to land?

On Mon, Jun 24, 2019 at 7:21 PM Todd Volkert <notifications@github.com>
wrote:

> Nope
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/dart-lang/http_server/pull/57?email_source=notifications&email_token=AAAEFCRF4EE33RHRKCWS2XTP4F6JRA5CNFSM4H2XN572YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYOYOGI#issuecomment-505251609>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAAEFCSFNLI3YTP32AT7H6LP4F6JRANCNFSM4H2XN57Q>
> .
>

2019-06-25 02:26 UTC, merged

2019-06-25 02:30 UTC, tvolkert commented
Yes please (thanks!)